import "./globals.css";
import { Inter } from "next/font/google";
import { GlobalContextProvider } from "./Context/store";
import Layout from "./components/Layout/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContextProvider>
          <Layout>{children}</Layout>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
